### PR TITLE
Add clientId and nl to be used in the bridged connection

### PR DESCRIPTION
**Pull request by oldrich-s**
Part of a fix for: https://github.com/moscajs/aedes/issues/736

### CODE REVIEW

**Comment by robertsLando** [comment]
fix tests

**Comment by oldrich-s** [comment]
I added new unit tests and made existing unit tests not fail.

**Review by robertsLando — APPROVED** [review]

**Comment by robertsLando** [comment]
@mcollina @gnought thoughts on this?

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by robertsLando** [comment]
@mcollina I was going to release version 3 but I'm not a collaborator of aedes-packet on npm. Could you fix this?

**Pull request merged**
