### PR TITLE
Added a missing dup field

### PR DESCRIPTION
**Pull request by gnought**

### CODE REVIEW

**Comment by mcollina** [comment]
tests are failing.

**Comment by gnought** [comment]
Aedes does not take care of `dup` flag. It needs to include it to stick to the spec. However this change will be massively affect other aedes-related packages.
Review later. :)

**Comment by mcollina** [comment]
CI is failing.

**Comment by robertsLando** [comment]
@mcollina Was just a typo :)

**Comment by mcollina** [comment]
Could you add a unit test?

**Comment by robertsLando** [comment]
@mcollina Tests are fixed now

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by robertsLando** [comment]
@mcollina Release?

**Pull request merged**
